namespace: atomist
name: github-repo-config-skill
displayName: GitHub Repo Config Skill
description: Share configurations across Repos
license: unknown
author: atomist
triggers:
  - OnNewRepo
  - OnSchedule
resourceProviders:
  - name: github
    description: GitHub
    typeName: GitHubAppResourceProvider
    minRequired: 1
    maxAllowed: 1
  - name: chat
    displayName: Chat
    typeName: ChatProvider
    description: Chat
    minRequired: 0
    maxAllowed: 1
commands:
  - name: sync
    description: check all the Repo configs
    pattern: ^sync repo config.*$
iconUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
homepageUrl: "https://github.com/atomist-skills/github-repo-config-skill"
parameters:
  - string:
      description: list the Repo topic you use to set this policy
      displayName: Choose Topic
      name: topic
      placeHolder: topicname
      required: true
  - string:
      description: >-
        see
        [documentation](https://developer.github.com/v3/repos/#update-a-repository)
      displayName: GitHub Repo Config
      name: repoConfig
      lineStyle: multiple
      placeHolder: '{"has_wiki": false, "has_issues": false}'
      required: true
  - schedule:
      description: check regularly
      displayName: schedule
      name: schedule
      defaultValue: 0 */6 * * *
      placeHolder: 0 */6 * * *
      required: false
  - repoFilter:
      description: Select repositories that should have the standard set of Labels
      displayName: Repo Filter
      name: RepoFilter
      required: false
artifacts:
  gcf:
    - entryPoint: eventhandler
      runtime: nodejs10
      name: do-it-on-node
      memory: 512
      timeout: 60
